name: provider_devtools_extension
description: "The Flutter web app for the package:provider DevTools extension."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.18.0
  devtools_extensions: ^0.2.2
  devtools_app_shared: ^0.2.2
  flutter_riverpod: ^2.5.1
  logging: ^1.1.1
  vm_service: ^14.2.5
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  freezed: ^2.5.7
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
